# frozen_string_literal: true

source "http://rubygems.org"
gem "nokogiri"
gem "fastimage" # get image attributes, even from a url
gem "aasm"
gem "andand"
gem "cloudinary", git: "https://github.com/cloudinary/cloudinary_gem"
#gem "debase"
gem "free-image" # image manipulation, at a basic level
gem "mechanize"
#gem "mongo"
gem "puma"
gem "rails"
gem "rerun", git: "https://github.com/alexch/rerun"
#gem "rmagick"
gem "roda", git: "https://github.com/jeremyevans/roda" # alternative to sinatra; look into
gem "ruby-debug-ide"
#gem "ruby-vips"
gem "sequel" # database that has the same author as roda
#gem "shotgun"
gem "sinatra"
gem "solargraph"
gem "rubocop"
gem "sinatra-contrib"
#gem "statemachine"
gem "telegram_bot"
gem "time_difference"#, git: "https://github.com/ZeroPivot/time_difference" # time difference algorithm (https://github.com/tmlee/time_difference)
gem "twitter"
gem "tzinfo"
gem "webrick"
gem "yaml"
gem "padrino"
gem 'wdm' # For Windows Ruby Only
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw]
gem "ruby2d"
gem "state_machine"
# gem "image_pro:wqcessing", git: "https://github.com/ZeroPivot/image_processing"
