module FileMethods
  DB_LIST: "./db/db_list.txt"

  DB_DIR: "./db"

  def make_db: (?untyped db_dir) -> untyped

  def read_lines: (untyped array) -> untyped

  def read_multi_string: (untyped string) -> untyped

  def read_file_lines: (?untyped file_name) -> untyped

  def write_line: (untyped line, ?untyped filename) -> (nil | untyped)

  def remove_line: (untyped line, ?untyped filename) -> untyped

  def check_file_duplicates: (untyped check, ?untyped filename) -> untyped

  def array_duplicates?: (untyped check, untyped array_of_strings) -> untyped

  def write_lines: (untyped lines_array, ?untyped filename) -> untyped
end
